server:
  port: 8080
  servlet-path: /hotel-manage

spring:
  application:
    name: "hotel-manage-web"

  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
  jpa:
    hibernate:
      ddl-auto: none
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level: debug