server:
  port: 6666
  servlet-path: /hotel-manage

spring:
  application:
    name: "hotel-manage-web"

  jackson:
    default-property-inclusion: non_null

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  aop:
    proxy-target-class: true


alibaba:
  druid:
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:

logging:
  level:
    com.hotel: debug
    org.hibernate.SQL: debug
    org.springframework: debug
  file: hotel.log