spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level: debug
  config:
